about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.about, name='index'),
]

kirabot/urls.py
from django.urls import path
from . import views
# from django.conf.urls import url


app_name = 'kirabot'

urlpatterns = [
    path('', views.ChatterBotAppView.as_view(), name='index'),
    path('api/', views.ChatterBotApiView.as_view(), name='kirabotapi'),
]

kirabot/views.py
import json
from django.views.generic.base import TemplateView
from django.views.generic import View
from django.http import JsonResponse
from chatterbot import ChatBot
from chatterbot.ext.django_chatterbot import settings
from chatterbot.trainers import ChatterBotCorpusTrainer


class ChatterBotAppView(TemplateView):
    template_name = 'kirabot/kira.html'


class ChatterBotApiView(View):
    """
    Provide an API endpoint to interact with ChatterBot.
    """

    kira = ChatBot('Kira',
                   database_uri='sqlite:///kira.sqlite3',
                   storage_adapter='chatterbot.storage.SQLStorageAdapter',
                   logic_adapters=[
                       {
                           'import_path': 'chatterbot.logic.BestMatch',
                           'statement_comparison_function': 'chatterbot.comparisons.levenshtein_distance'
                       },
                       {
                           'import_path': 'chatterbot.logic.MathematicalEvaluation'
                       },
                       # {
                       #     'import_path':'chatterbot.logic.TimeLogicAdapter'
                       # }
                   ],

                   # works just fine
                   # trainer = 'chatterbot.trainers.ChatterBotCorpusTrainer',
                   # training_data = ['./customcorpus.yml','chatterbot.corpus.english','chatterbot.corpus.french']

                   )

    # trainer = ChatterBotCorpusTrainer(kira)
    # trainer.train('./customcorpus.yml',
    #               'chatterbot.corpus.english', 'chatterbot.corpus.french')

    def post(self, request, *args, **kwargs):
        """
        Return a response to the statement in the posted data.

        * The JSON data should contain a 'text' attribute.
        """
        input_data = json.loads(request.body.decode('utf-8'))

        if 'text' not in input_data:
            return JsonResponse({
                'text': [
                    'The attribute "text" is required.'
                ]
            }, status=400)

        response = self.kira.get_response(input_data)

        response_data = response.serialize()

        return JsonResponse(response_data, status=200)

    def get(self, request, *args, **kwargs):
        """
        Return data corresponding to the current conversation.
        """
        return JsonResponse({
            'name': self.kira.name
        })

templates/kirabot/kira.html
{% load staticfiles %}

{% block css %}
<link href="{% static '/css/kira.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
<div class="row kirabot">
  <div class="col-xs-6 offset-xs-3">
    <ul class="list-group kira-log js-chat-log">
    </ul>

    <div class="input-group input-group-lg mt-1">
      <input type="text" class="form-control js-text" placeholder="Type something to begin..." />
      <span class="input-group-btn">
        <button class="btn btn-primary js-say">Submit</button>
      </span>
    </div>

  </div>
</div>

<script>
  var chatterbotUrl = '{% url "kirabot:kirabotapi" %}';
  var csrftoken = Cookies.get( 'csrftoken' );
  var cur_time = new Date().toLocaleTimeString( navigator.language, { hour: '2-digit', minute: '2-digit' } );

  function csrfSafeMethod( method )
  {
    // these HTTP methods do not require CSRF protection
    return ( /^(GET|HEAD|OPTIONS|TRACE)$/.test( method ) );
  }

  $.ajaxSetup( {
    beforeSend: function ( xhr, settings )
    {
      if ( !csrfSafeMethod( settings.type ) && !this.crossDomain )
      {
        xhr.setRequestHeader( "X-CSRFToken", csrftoken );
      }
    }
  } );

  var $chatlog = $( '.js-chat-log' );
  var $input = $( '.js-text' );
  var $sayButton = $( '.js-say' );

  function createRow( text )
  {
    var $row = $( '<li class="list-group-item"></li>' );

    $row.text( text );
    $chatlog.append( $row );
  }

  function submitInput()
  {
    var inputData = {
      'text': $input.val()
    }

    // Display the user's input on the web page
    createRow( inputData.text );

    var $submit = $.ajax( {
      type: 'POST',
      url: chatterbotUrl,
      data: JSON.stringify( inputData ),
      contentType: 'application/json'
    } );

    $submit.done( function ( statement )
    {
      createRow( statement.text );

      // Clear the input field
      $input.val( '' );

      // Scroll to the bottom of the chat interface
      $chatlog[ 0 ].scrollTop = $chatlog[ 0 ].scrollHeight;
    } );

    $submit.fail( function ()
    {
      // TODO: Handle errors
    } );
  }

  $sayButton.click( function ()
  {
    submitInput();
  } );

  $input.keydown( function ( event )
  {
    // Submit the input when the enter button is pressed
    if ( event.keyCode == 13 )
    {
      submitInput();
    }
  } );
</script>
{% endblock content %}

templates/kirabot/kira2.html
{% load staticfiles %}


{% block content %}

<div class="kiracard card kirabot">

	<div class="card-header msg_head p-1">
		<div class="d-flex bd-highlight">
			<div class="img_cont">
				<img src="{% static '/img/kira2.png' %}" class="rounded-circle user_img">
			</div>
			<div class="user_info">
				<span>Kira</span>
			</div>
		</div>

	</div>

	<!-- msg list -->
	<ul class="card-body msg_card_body js-chat-log">

		<div class="d-flex mb-4 justify-content-start">
			<div class="img_cont_msg">
				<img src="{% static '/img/kira2.png' %}" class="rounded-circle user_img_msg">
			</div>
			<div class="msg_container">
				Hello {{ user.first_name }}
				<span class="msg_time"> {% now "H:i" %} </span></div>
		</div>

	</ul>

	<div class="card-footer">
		<div class="input-group">
			<textarea name="js-text" type="text" class="form-control js-text"
				placeholder="Type your message..."></textarea>
			<div class="input-group-append">
				<button class="js-say input-group-text send_btn"><i class="fas fa-location-arrow"></i></button>
			</div>
		</div>
	</div>
</div>


<script>
	var $chatlog = $( '.js-chat-log' );
	var $input = $( '.js-text' );
	var $sayButton = $( '.js-say' );

	var chatterbotUrl = '{% url "kirabot:kirabotapi" %}';
	var csrftoken = Cookies.get( 'csrftoken' );

	function csrfSafeMethod( method ) {
		// these HTTP methods do not require CSRF protection
		return ( /^(GET|HEAD|OPTIONS|TRACE)$/.test( method ) );
	}

	$.ajaxSetup( {
		beforeSend: function ( xhr, settings ) {
			if ( !csrfSafeMethod( settings.type ) && !this.crossDomain ) {
				xhr.setRequestHeader( "X-CSRFToken", csrftoken );
			}
		}
	} );

	var $chatlog = $( '.js-chat-log' );
	var $input = $( '.js-text' );
	var $sayButton = $( '.js-say' );

	function kiramsg( msg ) {
		let cur_time = new Date().toLocaleTimeString( navigator.language, {
			hour: '2-digit',
			minute: '2-digit'
		} );

		return $( '<div class="d-flex mb-4 justify-content-start">' +
			'<div class="img_cont_msg" >' +
			"<img src='{% static '/img/kira2.png' %}' class='rounded-circle user_img_msg' ></div >" +
			'<div class= "msg_container" > ' +
			msg +
			'<span class="msg_time">' + cur_time + ' </span></div ></div >'
		);
	}

	function usermsg( msg ) {
		let cur_time = new Date().toLocaleTimeString( navigator.language, {
			hour: '2-digit',
			minute: '2-digit'
		} );

		return $( '<div class="d-flex mb-4 justify-content-end">' +
			'<div class="msg_container_send">' +
			msg +
			'<span class="msg_time_send">' + cur_time + '</span></div ><div class="img_cont_msg" >' +
			"<img src= '{% static '/img/Victor.jpg' %}' class='rounded-circle user_img_msg'></div></div>"
		);
	}


	function createRow( text ) {
		$chatlog.append( text );
	}

	function submitInput() {
		var inputData = {
			'text': $input.val()
		}

		// Display the user's input on the web page
		createRow( usermsg( inputData.text ) );

		var $submit = $.ajax( {
			type: 'POST',
			url: chatterbotUrl,
			data: JSON.stringify( inputData ),
			contentType: 'application/json'
		} );

		$submit.done( function ( statement ) {

			createRow( kiramsg( statement.text ) );

			// Clear the input field
			$input.val( '' );

			// Scroll to the bottom of the chat interface
			$chatlog[ 0 ].scrollTop = $chatlog[ 0 ].scrollHeight;
		} );

		$submit.fail( function () {
			createRow( 'sorry, something happened and I could not reach my source :)' );
		} );
	}

	$sayButton.click( function () {
		submitInput();
	} );

	$input.keydown( function ( event ) {
		// Submit the input when the enter button is pressed
		if ( event.keyCode == 13 ) {
			submitInput();
		}
	} );

</script>


{% endblock content %}