about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.about, name='index'),
]

desks/urls.py
from django.urls import path
from . import views

app_name = 'desks'

urlpatterns = [
    path('', views.index, name='index'),
    path('waf/', views.waf, name='waf'),
    path('card-detail/', views.card_detail, name='detail'),
    path('reply/', views.reply, name='reply'),
    path('vote/', views.vote, name='vote'),
]

library/urls.py
from django.urls import path
from .views import (library, view_count, flag_video,
                    read, books, watch, upload_video)

app_name = 'library'


urlpatterns = [
    path('', library, name='index'),
    path('books/', books, name='books'),
    path('video/upload/', upload_video, name='upload_video'),
    path('watch/<int:video_id>', watch, name='watch'),
    path('view-count/', view_count, name='view_count'),
    path('read/<int:doc_id>/', read, name='read'),
    path('flag-video/<int:video_id>/', flag_video, name='flag_video'),

    # ajax load related videos -> TODO: Moved to update => watch loads all
    # path('watch/similar/<title>', related_watch, name='related_watch'),
]

templates/401.html
{% extends 'base.html' %}

{% block content %}
<div class="row pt-5">
    <div class="col-12 text-center">
        <h1 class="text-primary py-2" style="font-size: 4rem;">Unauthorized</h1>
        <h2>401 error</h2>
        <p>You ain't authorized to do that!</p>
        <a href="{% url 'login' %}" class="btn btn-success">spice me up! <i class="fa fa-arrow-left"></i>
        </a>
    </div>
</div>
{% endblock content %}

templates/_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en-US">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
		<meta name="authors" content="Victor Nara" />
		<meta
			name="description"
			content="social learning community to educate, learn, promote talents and share knowledge, experience and culture"
		/>
		<meta name="mobile-web-app-capable" content="yes" />
		<meta name="apple-mobile-web-app-title" content="Waffle" />
		<meta name="apple-mobile-web-app-status-bar-style" content="white" />
		<meta name="theme-color" content="#F5F9FC" />

		<link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet" />
		<link href="{% static '/css/all.min.css' %}" rel="stylesheet" />
		<link href="{% static '/css/app/styles.css' %}" rel="stylesheet" />

		<!-- unique page specific css here -->
		{% block css %} {% endblock %}
		<!-- end of page specific css -->

		<link
			href="{% static '/img/waffle-new-logo.png' %}"
			type="image/jpg"
			rel="shortcut icon"
		/>

		<!-- Global site tag (gtag.js) - Google Analytics -->
		<!-- <script async src="https://www.googletagmanager.com/gtag/js?id=UA-156274014-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];

      function gtag() {
        dataLayer.push( arguments );
      }
      gtag( 'js', new Date() );

      gtag( 'config', 'UA-156274014-1' );

    </script> -->

		<title>
			{% block title %} {% endblock %} - Waffle
		</title>
	</head>

	<body>
		<!-- Navigation -->
		{% include '_nav.html' %}

		<main class="container mt-4 pt-3">
			{% block content %} {% endblock %}
		</main>

		<main class="container-fluid mt-2">
			<!-- for fluid template layouts -->
			{% block fluid %} {% endblock %}
		</main>

		<!-- footer -->
		<footer></footer>

		<!-- core scripts -->
		<script src="{% static '/js/jquery.min.js' %}"></script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<!-- <script src="{% static 'js/js.cookie.js' %}"></script> -->
		<!-- <script src="{% static 'js/app/app.js' %}"></script> -->

		<!-- extra scripts -->
		{% block javascript %} {% endblock %}
	</body>
</html>

templates/_nav.html
{% load static %}

{% url 'library:index' as lib_url %}
{% url 'landing' as landing_url %}
{% url 'about:index' as about_url %}
{% url 'desks:index' as desk_url %}
{% url 'account_logout' as logout_url %}
{% url 'account_login' as login_url %}
{% url 'account_signup' as signup_url %}
{% url 'contact' as contact_url %}


<!--Navbar -->
<header class="navbar navbar-expand-lg fixed-top navbar-toggleable-md navbar-light text-light p-1" id="mainnav">
    <div class="container">
        <div class="d-flex">
            <a href="{{ landing_url }}">
                <img src="{% static '/img/waffle-new-logo.png' %}" class="d-inline-block align-top" width="40"
                    height="40" alt="Waffle Logo" />
                <span class="navbar-brand text-primary">
                    waffle
                </span>
            </a>
        </div>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#wafnav"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <nav class="collapse navbar-collapse" id="wafnav">

            <ul class="navbar-nav flex-row ml-auto justify-content-between">
                <li class="nav-item mr-1">
                    <a class="nav-link {% if request.path == lib_url %}text-primary{% endif %}"
                        href="{{ lib_url }}">library</a>
                </li>

                <!-- <li class="nav-item mr-1">
                    <a class="nav-link {% if request.path == about_url %}text-primary{% endif %}"
                        href="{{ about_url }}">about</a>
                </li> -->

                <li class="nav-item mr-1">
                    <a class="nav-link {% if request.path == contact_url %}text-primary{% endif %}"
                        href="{{ contact_url }}">contact</a>
                </li>

                {% if user.is_authenticated %}
                <li class="nav-item mr-1">
                    <a class="nav-link {% if request.path == desk_url %}text-primary{% endif %}"
                        href="{{ desk_url }}">desk</a>
                </li>

                <li class="nav-item avatar">
                    <img src="{{ user.profilepic_url }}" class="rounded-circle z-depth-0 mt-1" alt="user profile pic"
                        id="nav_profile_pic" height="30">
                </li>

                <div class="dropdown">
                    <a class="nav-link dropdown-toggle pl-0" href="#" role="button" id="dropdownMenuLink"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <span class="pl-2">{{ user.first_name }}</span>
                    </a>

                    <div class="dropdown-menu shadow-sm" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'profile' user.username %}">profile</a>

                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ logout_url }}">logout</a>
                    </div>
                </div>


                {% else %}

                <li class="nav-item mr-1">
                    <a class="authbtn nav-link" href="{{ login_url }}">login</a>
                </li>
                <li class="nav-item mr-3">
                    <a class="authbtn nav-link" href="{{ signup_url }}">signup</a>
                </li>

                {% endif %}

            </ul>


        </nav>
    </div>
</header>

templates/error.html
{% extends 'base.html' %}

{% block content %}


<div class="mt-4 bg-white rounder text-danger text-center shadow-sm p-3">
    <i class="fa fa-exclamation-circle  fa-10x pb-4" aria-hidden="true"></i>
    <p>
        Something happened. We will fix it soon :)
    </p>
</div>

{% endblock content %}

templates/scratchpad.html
{% extends 'base.html' %}

{% block content %}
<h2>Scratchpad coming soon....</h2>
<p>a virtual whiteboard for learning</p>
{% endblock content %}

templates/submenu.html
{% url 'library:index' as vid_url %}
{% url 'library:books' as bks_url %}


<div class="flex-row ml-auto justify-content-between row my-4">
    <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
        <!-- <div class="btn-group btn-group-sm" role="group" aria-label="First group">
            <a class="nav-item nav-link btn btn-outline-primary" href="{% url 'library:index' %}"><i
                    class="fas fa-film"></i> Videos</a>

            <a class="nav-item nav-link btn btn-outline-primary" href="{% url 'library:books' %}"><i
                    class="fas fa-book"></i> Files</a>
        </div> -->
    </div>
    <div class="btn-toolbar mr-3" role="toolbar" aria-label="Toolbar with button groups">
        <div class="btn-group btn-group-sm" role="group" aria-label="upload buttons">
            <a class="nav-item nav-link btn btn-outline-secondary" href="{% url 'library:upload_video' %}">
                <span class="fas fa-plus"></span> New Video
            </a>
            <!-- <a class="nav-item nav-link btn btn-outline-secondary" href="{% url 'library:index' %}">
                New File</a> -->
        </div>
    </div>
</div>