about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.about, name='index'),
]

desks/urls.py
from django.urls import path
from . import views

app_name = 'desks'

urlpatterns = [
    path('', views.index, name='index'),
    path('waf/', views.waf, name='waf'),
    path('card-detail/', views.card_detail, name='detail'),
    path('reply/', views.reply, name='reply'),
    path('vote/', views.vote, name='vote'),
]

desks/models.py
# standard
import datetime

# django
from django.db import models
from django.conf import settings


# local django
from .managers import *

# Create your models here.

# cards of questions

class Card(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    text = models.TextField(max_length=500)
    votes = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='CardVote',
        through_fields=('card', 'user'),
        related_name='card_votes',
    )
    card_date = models.DateField()
    card_time = models.TimeField()

    def __str__(self):
        return self.text

    def save(self, *args, **kwargs):
        self.card_date = datetime.datetime.now().date()
        self.card_time = datetime.datetime.now().time()

        super(Card, self).save(*args, **kwargs)

    # default model manager.. if not done, django will use the first manager as the default
    # once we are setting additional customer managers
    objects = models.Manager()
    # custom model managers


class CardReply(models.Model):
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    text = models.TextField(max_length=2000)
    reply_date = models.DateField()
    reply_time = models.TimeField()

    def __str__(self):
        return self.text

    def save(self, *args, **kwargs):
        self.reply_date = datetime.datetime.now().date()
        self.reply_time = datetime.datetime.now().time()

        super(CardReply, self).save(*args, **kwargs)


class CardVote(models.Model):
    card = models.ForeignKey(Card, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    vote = models.IntegerField(
        default=0,
        help_text='determines whether a vote is up or down: 1 is upvote & 2 is downvote'
    )
    vote_date = models.DateField(auto_now_add=True)
    vote_time = models.TimeField(auto_now_add=True)


# reaction #1 = upvote &  2 = downvote

desks/views.py
# standard
import json

# django
from django.shortcuts import render
from django.core import serializers
from django.http import Http404, HttpResponse, JsonResponse
from django.forms.models import model_to_dict
from django.contrib.auth.decorators import login_required
from django.urls import resolve
from django.template import loader
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_GET, require_POST
from django.db.models import Count, Q

# local django
from logs.utils import log_error
from waffle.utils import errMsg
from .models import (Card, CardVote, CardReply)
from desks.utils import (replyCount,
                         upvoteCount,
                         downvoteCount,
                         vote as cast_vote,
                         Vote)


# Create your views here.

@login_required
@require_GET
def index(request):
    cards = Card.objects.order_by(
        *['-card_date', '-card_time']).annotate(replies=Count('cardreply')).select_related('user').all()

    # upvote = Count('cardvote__vote', filter=Q(cardvote__vote='1'))
    # downvote = Count('cardvote__vote', filter=Q(cardvote__vote='2'))
    # c = Card.objects.annotate(replies=Count('cardreply')).annotate(
    #     upvotes=upvote).annotate(downvotes=downvote).values('replies','upvotes','downvotes')

    return render(request,
                  'desks/index.html',
                  {'cards': cards,
                   })


@login_required
@require_POST
def waf(request):
    if request.method == 'POST' and request.is_ajax():
        post_text = request.POST['text']

        card = Card.objects.create(
            text=post_text,
            user=request.user
        )

        card_obj = model_to_dict(card)
        first_name = request.user.first_name
        username = request.user.username

        return JsonResponse({'error': False,
                             'data': card_obj,
                             'first_name': first_name,
                             'username': username},
                            status=200)

    else:
        return JsonResponse({"success": False,
                             'msg': 'An error has occured'},
                            status=400)


@login_required
@require_GET
def card_detail(request):
    try:
        if request.is_ajax():
            m = request.GET['magic']

            if not m:
                return JsonResponse({'err': 'invalid selection'}, status=400)

            # prefetch good for many to many relations : fetches card & related votes
            c = Card.objects.prefetch_related('votes').get(pk=m)

            r = CardReply.objects.filter(card=c.id).select_related('user').values(
                'text', 'user__username', 'user__first_name', 'user__last_name', 'user__profile_pic',  'reply_date', 'reply_time')

            # render template with dic values and return template as string literals
            html = loader.render_to_string('desks/partials/card_detail.html', {
                'card': c,
                'replies': r,
                'upvotes': upvoteCount(c, False),
                'downvotes': downvoteCount(c, False),
                'replycount': r.count(),
            })
            # pass template string literals into json to be parsed backed into html
            return JsonResponse({'html': html}, status=200)

    except Exception as e:
        log_error(
            str(type(e)),
            e,
            'desks - card_detail',
            url=resolve(request.path_info).url_name)
        return errMsg('Something went wrong')
        # return e


@login_required
@require_POST
def reply(request):
    try:
        if request.method == 'POST' and request.is_ajax():
            r = CardReply.objects.create(
                card_id=request.POST['card_id'],
                user=request.user,
                text=request.POST["reply"],
            )
            m = model_to_dict(r)
            first_name = request.user.first_name
            username = request.user.username
            return JsonResponse(
                {
                    'reply': m,
                    'count': replyCount(r.card),
                    'status': 'OK',
                    'first_name': first_name,
                    'username': username
                },
                status=200)

    except Exception as e:
        log_error(
            str(type(e)),
            e,
            'desks - reply',
            url=resolve(request.path_info).url_name
        )
        return errMsg('Something went wrong')


@login_required
@csrf_exempt
@require_POST
def vote(request):
    try:
        print('yeah go inside vote --- but its empty :( So what do u want here?')
        # card_id = request.POST['card']
        # vote = 0
        # print('vote view called inside django')

        # if str(request.POST['voteType']).lower() == 'up':
        #     vote = cast_vote('1', card_id, request.user)
        # elif str(request.POST['voteType']).lower() == 'down':
        #     vote = cast_vote('2', card_id, request.user)

        # return JsonResponse(
        #     {
        #         'vote': vote,
        #         'upvotes': upvoteCount(card_id, True),
        #         'downvotes': downvoteCount(card_id, True)
        #     }, status=200)

    except Exception as e:
        log_error(
            str(type(e)),
            e,
            'desks - vote',
            url=resolve(request.path_info).url_name)
        return errMsg('Vote not cast')
        # return e

templates/desks/partials/card_detail.html
{% load static %} {% block javascript %}
<script>
	function paintReply(r, card_id) {
		$l = $(
			'<div class = "reply-container">' +
				'<div class = "reply-head">' +
				"<img src='../static/img/profile_pics/default.jpg'" +
				' class = "card-user-pic rounded-circle z-depth-0 mt-1" alt = "profile pic"  height = "30">' +
				"<span> <strong>" +
				r.first_name +
				"</strong> ~ @" +
				r.username +
				"</span>" +
				'<div class="ml-4"> <small> Now' +
				'</small></div> </div><div><p class = "p-2 ml-4 reply-text">' +
				r.reply["text"] +
				"</p> </div> </div>"
		);

		$("#replies").append($l);
		$("#reply").css("height", "auto").val("");
		$("#d-count").text(r.count);
		$(`#${card_id}count`).text(r.count); //update non-detailed parent card that was clicked on
		$("#reply-status").text("");
	}

	//detailed view upvote click
	$(".upvotes").click(function () {
		card = $(this).closest("div.reactions").attr("data-magic");
		vote("up", card, "{% url 'desks:vote' %}", true);
	});

	//detailed view downvote click
	$(".downvotes").click(function () {
		card = $(this).closest("div.reactions").attr("data-magic");
		vote("down", card, "{% url 'desks:vote' %}", true);
	});

	function reply(card_id) {
		$.ajax({
			type: "POST",
			url: "{% url 'desks:reply' %}",
			dataType: "json",
			data: {
				card_id: card_id, //card id
				reply: $("#reply").val(),
				csrfmiddlewaretoken: $("input[name=csrfmiddlewaretoken]").val(),
			},
			beforeSend: function () {
				$("#reply-status").text("replying...");
			},
			success: function (r) {
				paintReply(r, card_id);
			},
			error: function (xhr, errmsg, err) {
				$("#reply-status").text(err);
			},
		});
	}
</script>
{% endblock %} {% block content %}

<div class="media m-0 py-3 mb-5" id="desk-card-detail">
	<input type="hidden" id="d-vote" value="{{vote}}" />

	<img
		src="{{ card.user.profile_pic.url }}"
		class="ml-2 card-user-pic rounded-circle z-depth-0 mt-1"
		alt="profile image"
		height="30"
	/>

	<div class="media-body">
		<div class="float-right mr-3 text-primary" id="detail-back">
			<span
				class="fa fa-arrow-left"
				data-toggle="modal"
				data-target="#waf-detail"
			>
			</span>
		</div>

		<div class="pt-1 ml-2">
			<span class="username">{{ card.user.fullname }}</span>
			<div>
				<span class="text-muted">@{{card.user.username}} ~ </span>
				<small class="text-muted"> {{card.card_date}}</small>
				<p id="diagmsg"></p>
			</div>
		</div>

		<div class="px-2">
			<p class="py-2 card-text">
				{{card.text}}
			</p>
			<footer>
				<hr />
				<div class="reactions" data-magic="{{card.id}}">
					<span class="pr-2 text-muted"
						><i class="reply-count far fa-comment-alt"></i>
						<span id="d-count">{{replycount}} </span><small> replies</small>
					</span>
					<!-- <span class="pr-2 text-muted">
                        <i class="upvotes fas fa-arrow-up"></i>
                        <span id="d-upvote">
                            {{upvotes}}
                        </span><small> upvotes</small>
                    </span>
                    <span class="text-muted">
                        <i class="downvotes fas fa-arrow-down"></i>
                        <span id="d-downvote">
                            {{downvotes}}
                        </span>
                        <small> downvotes</small>
                    </span> -->
				</div>
				<hr />

				<div id="replies">
					{% for r in replies %}
					<div class="reply-container">
						<div class="reply-head">
							<img
								src="{{ r.user__profile_pic.url }}"
								class="card-user-pic rounded-circle z-depth-0 mt-1"
								alt="profile image"
								height="30"
							/>
							<span class="username"
								>{{r.user__first_name}} {{r.user__last_name}} ~ </span
							><span>@{{r.user__username}}</span>
							<div class="ml-4">
								<small>{{r.reply_date|date:'D d, M'}}</small>
							</div>
						</div>
						<div class="reply-text-container">
							<p class="p-2 ml-4 reply-text">{{r.text}}</p>
						</div>
					</div>
					{% endfor %}
				</div>

				<div id="reply-status"></div>

				<div class="input-group" id="userreply">
					<img
						src="{{ card.user.profile_pic.url }}"
						id="reply-user-pic"
						class="mr-2 card-user-pic rounded-circle z-depth-0 mt-1"
						alt="profile image"
						height="30"
					/>

					<form id="reply-form" class="p-0 m-0">
						{% csrf_token %}
						<div class="form-row">
							<div class="form-group col-12">
								<textarea
									type="text"
									maxlength="2000"
									name="reply"
									class="form-control"
									placeholder="add a reply..."
									aria-label="reply"
									aria-describedby="reply"
									rows="1"
									id="reply"
								></textarea>
							</div>
						</div>
					</form>
				</div>
			</footer>
		</div>
	</div>
</div>
{% endblock content %}

templates/desks/partials/cards.html
{% load static %}


{% block javascript %}
<script>
    function load_detail( magic ) {
        window.scrollTo( 0, 0 );

        $.ajax( {
            type: 'GET',
            url: "{% url 'desks:detail' %}",
            dataType: 'json',
            data: {
                'magic': magic,
            },
            beforeSend: function () {
                $( ".lds-ring" ).toggleClass( 'd-none' );
                $( "#desk-detail" ).html( '' );
            },
            success: function ( d ) {
                $( ".lds-ring" ).toggleClass( 'd-none' );
                $( "#desk-detail" ).html( d.html );
            },
            error: function ( xhr, errmsg, err ) {
                console.log( 'error' );
                $( ".lds-ring" ).removeClass( 'd-none' );

            },
        } );
    }

</script>
{% endblock %}


{% for card in cards %}

<div class="media m-0 deskcard py-3">
    <input type="hidden" id="{{card.id}}vote" value="{{vote}}">

    <img src="{{ card.user.profile_pic.url }}" class="ml-2 rounded-circle z-depth-0 mt-1 profilepic" alt="profile pic"
        height="30">

    <div class="media-body">

        <div class="pl-3 pr-2">
            <div class="py-2">
                <span class="username">{{card.user.fullname}}</span>
                <span class="text-muted">@{{card.user.username}}</span>
            </div>

            <div class="card-menu" data-magic="{{card.id}}">
                <p class="py-0 pb-1 card-text">{{card.text}}</p>
            </div>
            <small class="text-muted"> {{ card.card_date|date:'d, M' }}</small>

            <footer>
                <hr>
                <div class="reactions" data-magic="{{card.id}}">
                    <span class="pr-5 mr-2 text-muted"><i class="reply-count far fa-comment-alt"></i>
                        <span class="pl-1 cards-count" id="{{card.id}}count">{{card.replies}} replies</span>
                    </span>
                    <!-- <span class="pr-5 mr-3 text-muted"><i class="upvotes fas fa-arrow-up"></i>
                        <span class="pl-1 cards-upvote" id="{{card.id}}upvote">
                            {{upvotes}}
                        </span>
                    </span>
                    <span class="text-muted">
                        <i class="downvotes fas fa-arrow-down"></i>
                        <span class="pl-1 cards-downvote" id="{{card.id}}downvote">
                            {{downvotes}}
                        </span>
                    </span> -->
                </div>
            </footer>
        </div>
    </div>
</div>

{% endfor %}

<p class="text-muted text-center pt-4">Looks like you've reached the end</p>

templates/desks/partials/communities.html
<div class="media mb-2 comm">
    <i style="color: pink;" class="p-2 fas fa-atom fa-3x"></i>
    <div class="media-body">
        <h6 class="pt-2 pl-3">Sci-Ladies</h6>
        <div class="text-secondary pl-3">24k members</div>
    </div>
</div>
<div class="media mb-2 comm">
    <i style="color: blueviolet;" class="p-2 fas fa-square-root-alt fa-3x"></i>
    <div class="media-body">
        <h6 class="pt-2 pl-3">E - Maths</h6>
        <div class="text-secondary pl-3">74k members</div>
    </div>
</div>
<div class="media mb-2 comm">
    <i class="p-2 fas fa-street-view fa-3x"></i>
    <div class="media-body">
        <h6 class="pt-2 pl-3">Meditate Me</h6>
        <div class="text-secondary pl-3">751 members</div>
    </div>
</div>

templates/desks/partials/sponsoredcomms.html
<div class="media mb-2 comm">
    <i style="color: yellowgreen;" class="p-2 fas fa-ad fa-3x"></i>
    <div class="media-body">
        <h6 class="pt-2 pl-3">Sponsored Ad</h6>
        <a href="#" class="text-secondary pl-3">visit us</a>
    </div>
</div>

templates/desks/partials/waf.html
{% load static %}

<div class="modal fade" id="wafpost" tabindex="-1" role="dialog" aria-labelledby="wafpostLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h6 class="modal-title text-secondary" id="exampleModalLabel">change the world!</h6>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="waf-form">
                    {% csrf_token %}
                    <div class="form-group">
                        <!-- <label for="message-text" class="col-form-label">Message:</label> -->
                        <textarea rows="6" class="form-control" id="waf_text" placeholder="educate, ask or promote a talent"
                            name="waf_text" maxlength="500"></textarea>
                    </div>

                    <div class="waf-info text-primary">
                    </div>
                    <span id="waf-error" class="text-danger"></span>

                    <div class="d-flex justify-content-end">
                        <button type="submit" class="btn btn-primary" id="waf">
                            <i class="fa fa-paper-plane"></i> Waf
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="waffing" tabindex="-1" role="dialog" aria-labelledby="waffingTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="lds-ring">
                    <div></div>
                    <div></div>
                    <div></div>
                    <div></div>
                </div>
                <!-- <span id="msg">Waffing...</span> -->
            </div>
        </div>
    </div>
</div>