about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('', views.about, name='index'),
]

library/urls.py
from django.urls import path
from .views import (library, view_count, flag_video,
                    read, books, watch, upload_video)

app_name = 'library'


urlpatterns = [
    path('', library, name='index'),
    path('books/', books, name='books'),
    path('video/upload/', upload_video, name='upload_video'),
    path('watch/<int:video_id>', watch, name='watch'),
    path('view-count/', view_count, name='view_count'),
    path('read/<int:doc_id>/', read, name='read'),
    path('flag-video/<int:video_id>/', flag_video, name='flag_video'),

    # ajax load related videos -> TODO: Moved to update => watch loads all
    # path('watch/similar/<title>', related_watch, name='related_watch'),
]

library/models.py
# standard
import os
import uuid

# django
from django.db import models
from django.conf import settings
from django.utils.timezone import now


# Create your models here.

def slugify(self, title):
    return self.title.replace(" ", "-")


def video_filename_generator(instance, filename):
    ext = filename.split('.')[-1]
    new_name = f"{uuid.uuid4()}.{ext}"
    return os.path.join('video/', new_name)


def thumbnail_filename_generator(instance, filename):
    ext = filename.split('.')[-1]
    new_name = f"{uuid.uuid4()}.{ext}"
    return os.path.join('img/thumbnails/', new_name)


class Video(models.Model):
    title = models.CharField(max_length=100, blank=False)
    description = models.TextField(blank=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    upload_date = models.DateField(
        auto_now_add=True, null=True)
    publish_date = models.DateField(auto_now_add=True)
    publish_time = models.TimeField(auto_now_add=True)
    slug = models.SlugField(max_length=100, allow_unicode=True)
    deleted = models.BooleanField(
        default=False, help_text="deleted videos will not show in library n searches")
    # category = models.TextChoices()
    flagged = models.BooleanField(
        default=False,
        help_text="switch to take down video based on crowd source flagging as inappropriate"
    )
    duration = models.IntegerField(default=0, blank=False)

    # many to many fields
    views = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='VideoView',
        through_fields=('video', 'user'),
        related_name='video_views'
    )

    flags = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='VideoFlag',
        through_fields=('video', 'user'),
        related_name='video_flags'
    )

    # upload fields
    video = models.FileField(upload_to=video_filename_generator)
    thumbnail = models.ImageField(upload_to=thumbnail_filename_generator)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self, self.title)
        super(Video, self).save(*args, **kwargs)


class VideoView(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE, null=True)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    # location
    country = models.CharField(max_length=50, null=True)
    state = models.CharField(max_length=50, null=True)
    city = models.CharField(max_length=50, null=True)
    # navigator
    ip_address = models.CharField(max_length=50, null=True)
    user_agent = models.CharField(max_length=150, null=True)
    platform = models.CharField(max_length=150, null=True)
    # connection_speed = models.CharField(max_length=50, null=True)
    language = models.CharField(max_length=50, null=True)
    # timing
    view_date = models.DateField(auto_now_add=True)
    view_time = models.TimeField(auto_now_add=True)

    def __str__(self):
        return self.video.title


class VideoFlag(models.Model):
    video = models.ForeignKey(Video,
                              on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    flag_date = models.DateField(auto_now_add=True)
    flag_time = models.TimeField(auto_now_add=True)
    reason = models.CharField(max_length=300)

    def __str__(self):
        return self.video

# VIDEO COMMENTS

library/forms.py
from django import forms
from .models import Video, VideoView, VideoFlag


class VideoUploadForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = (
            'title', 'video', 'description',
        )


class VideoViewForm(forms.ModelForm):
    class Meta:
        model = VideoView
        fields = (
            'video', 'country', 'state',
            'city', 'ip_address', 'user_agent',
            'platform', 'language',
        )


class VideoFlagForm(forms.ModelForm):
    class Meta:
        model = VideoFlag
        fields = (
            'video', 'user', 'reason',
        )

library/views.py
# standard
import json
import os

from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.files.uploadedfile import UploadedFile
from django.db.models import Q, Count
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.http import require_GET, require_http_methods, require_POST
from django.forms.models import model_to_dict
from django.core.mail import send_mail
from django.views.decorators.csrf import csrf_exempt

# local
from .forms import VideoUploadForm, VideoViewForm
from .models import Video, VideoView

# django


# Create your views here.


def library(request):
    # pull all undeleted videos ordered by new
    # TODO: PUT ALL DB ACCESS CODE (ALL APPS) INTO A COMMON FILE WHERE METHODS WOULD
    #  REQUIRE NUMBER OF RECORDS TO PULL ETC.
    v = Video.objects.filter(deleted=False).order_by(
        *['-publish_date', '-publish_time']
    ).all()
    return render(request, 'library/library.html', {'vid': v})


def books(request):
    return render(request, 'library/books.html')


def watch(request, video_id):
    try:
        # current video in watch
        vid = Video.objects.filter(
            deleted=False, flagged=False
        ).annotate(
            view_count=Count('videoview')
        ).prefetch_related(
            'user').order_by(
            *['-publish_date', '-publish_time']
        ).get(pk=video_id)

        # TODO: update this to be videos related to one been played
        # show 15 more videos excluding the current one
        related = Video.objects.filter(
            deleted=False, flagged=False
        ).annotate(
            view_count=Count('videoview')
        ).prefetch_related(
            'user'
        ).exclude(
            pk=vid.id
        ).order_by(
            *['-publish_date']
        )[0:15]

        return render(request, 'library/watch.html', {'vid': vid, 'related': related})
    except Exception:
        return render(request, 'library/watch_broken.html')


def read(request, doc_id):
    return render(request, 'library/read.html')


@login_required
@require_http_methods(['GET', 'POST'])
def upload_video(request):
    if request.method == 'POST':
        # TODO: 1. Video file size   2. File Format     3.  Content    4.
        # formats = ['.mp4', '.mov', '.mpeg', 'WebM', '.ogg', ]
        # check if file format is any of the specified

        frm = VideoUploadForm(request.POST, request.FILES)
        if frm.is_valid():
            m = Video()
            m.title = frm.cleaned_data['title']
            m.description = frm.cleaned_data['description']
            m.video = frm.cleaned_data['video']
            # m.thumbnail = frm.cleaned_data['thumbnail']
            m.user = request.user
            m.save()
            return JsonResponse({'msg': 'Upload Successful'}, status=200)
        else:
            return JsonResponse({'err': 'Invalid Data detected!'}, status=400)
    else:
        return render(request, 'library/upload_video.html')


@require_GET
def related_watch(request, title, start=None, end=None):
    try:
        # TODO: Add this to feature Update
        start = 0  # assign start to itself (function parameter) or zero
        end = 15
        # user_id = user_id or None

        # get videos by similar author, titles and/or category
        sim = Video.objects.filter(
            Q(deleted=False),
            Q(title__icontains=title) | Q(
                title__iexact=title) | Q(title__istartswith=title) | Q(title__iendswith=title),
            # Q(user=user_id)
        ).order_by(
            *['-publish_date']
        ).values(
            'title', 'id', 'publish_date', 'thumbnail'
        )[start:end]

        res = model_to_dict(sim)
        return JsonResponse({'title': res}, status=200)
    except Exception as e:
        return JsonResponse({"status": "error"}, status=400)


@require_POST
@csrf_exempt
def view_count(request):
    try:
        vw = VideoViewForm(request.POST)
        if vw.is_valid():
            v = VideoView()
            v.video = Video.objects.get(pk=request.POST['video'])
            v.country = request.POST['country']
            v.state = request.POST['state']
            v.city = request.POST['city']
            v.ip_address = request.POST['ip_address']
            v.user_agent = request.POST['user_agent']
            v.platform = request.POST['platform']
            v.language = request.POST['language']

            if request.user.is_authenticated:
                v.user = request.user
            v.save()
        return JsonResponse({"status": "OK"}, status=200)
    except Exception as e:
        print(f'error: {e}')
        return JsonResponse({"status": "Error"}, status=400)


@login_required
@require_POST
@csrf_exempt
def flag_video(request, video_id):
    # TODO: flag video n send myself an async email
    try:
        pass
    except Exception as e:
        pass

templates/library/books.html
{% extends '../_base.html' %}

{% load static %}

{% block content %}
{% include '../submenu.html' %}

<div class="row">

    <!-- Books Section -->
    <div class="col-md-9 col-12">

        <div class="row">
            <div class="col-md-4">
                <div class="media mb-2">
                    <img class="mr-2" src="{% static '/img/bk2.jpg' %}" width="130" height="170"
                        alt="Generic placeholder image">
                    <div class="media-body">
                        <h5 class="mt-0">E - Maths</h5>
                        <span class="small"><span class="text-sm text-primary">Author:</span> Aki-Ola</span>
                        <span class="small"><span class="text-primary">ISBN:</span> 145-201-G58</span>
                        <span class="small"><span class="text-primary">Pages:</span> 305</span> <br>
                        <span class="small"><span class="text-primary">Format:</span> PDF | EPUB</span>
                        <a href="{% url 'library:read' 87430 %}" class="mt-2 btn btn-sm btn-primary">
                            <span class="fa fa-book-open"></span> Read
                        </a>
                    </div>
                </div>
            </div>

        </div>

    </div>

    <!-- Recommendations -->
    <div class="col-md-3 col-12">

    </div>

</div>

{% endblock content %}

templates/library/library.html
{% extends '../_base.html' %}
{% load static %}

{% block title %}
Library
{% endblock %}

{% block content %}

{% include '../submenu.html' %}
<!-- <div class="row"> -->

<div class="librarycontent">
    <!-- main section -->

    <div class="row">
        {% for v in vid %}
        <div class="col-md-3 col-10 offset-md-0 offset-1">
            <a href="{% url 'library:watch' v.pk %}" class="videocard cardsize" title="{{v.title}}">
                <div class="shadow-sm mb-3">
                    <img src="{% static '/img/img2.jpg' %}" class="card-img-top " alt="...">
                    <div class="card-body py-1">
                        <p class="videotitle text-secondary mb-2">{{ v.title }}</p>
                        <div>
                            <span class="videotext text-primary">{{ v.user.first_name }}
                                {{v.user.last_name}}</span>
                            <span class="small d-block text-secondary">{{ v.video_date|date:'M, d'}}</span>
                        </div>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

templates/library/read.html
{% extends '../_base.html' %}

{% load static %}

{% block content %}
{% include '../submenu.html' %}

<div class="row">
    <!-- Book details -->
    <div class="col-md-2">
        <h5 class="text-success">Now Reading..</h5>
        <img class="mr-2" src="{% static '/img/bk2.jpg' %}" width="150" height="200" alt="Generic placeholder image"
            class="img-thumbnail" />
        <table class="table table-responsive">
            <tr>
                <td>
                    Download
                </td>
                <td align="right">
                    <i class="text-success fa fa-download"></i>
                </td>
            </tr>
            <tr>
                <td>
                    Read out
                </td>
                <td align="right">
                    <i class="text-success fa fa-volume-up"></i>
                </td>
            </tr>
        </table>
    </div>

    <!-- book read -->
    <div class="col-md-7">
        <iframe id="pdfreader" src="{% static '/books/one.pdf' %}">
        </iframe>
    </div>

    <!-- recommendations -->
    <div class="col-md-3">
        <h5 class="text-center">
            <span class="badge badge-success p-2">
                Recommended for you
            </span>
        </h5>

        <div class="media mb-2 pb-2">
            <img class="mr-2" src="{% static '/img/bk3.jpg' %}" width="130" height="170"
                alt="Generic placeholder image">
            <div class="media-body">
                <h5 class="mt-0">E - Maths</h5>
                <span class="small"><span class="text-sm text-primary">Author:</span> Aki-Ola</span>
                <span class="small"><span class="text-primary">ISBN:</span> 145-201-G58</span>
                <span class="small"><span class="text-primary">Pages:</span> 305</span> <br>
                <span class="small"><span class="text-primary">Format:</span> PDF | EPUB</span>
                <a href="{% url 'library:read' 87430 %}" class="mt-2 btn btn-sm btn-primary">
                    <span class="fa fa-book-open"></span> Read
                </a>
            </div>
        </div>

        <div class="media mb-2 pb-2">
            <img class="mr-2" src="{% static '/img/bk1.jpg' %}" width="130" height="170"
                alt="Generic placeholder image">
            <div class="media-body">
                <h5 class="mt-0">E - Maths</h5>
                <span class="small"><span class="text-sm text-primary">Author:</span> Aki-Ola</span>
                <span class="small"><span class="text-primary">ISBN:</span> 145-201-G58</span>
                <span class="small"><span class="text-primary">Pages:</span> 305</span> <br>
                <span class="small"><span class="text-primary">Format:</span> PDF | EPUB</span>
                <a href="{% url 'library:read' 87430 %}" class="mt-2 btn btn-sm btn-primary">
                    <span class="fa fa-book-open"></span> Read
                </a>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/library/upload_video.html
{% extends '../_base.html' %}
{% load static %}

{% block title %}
Upload Video
{% endblock %}

{% block css %}

<style>
    video,
    canvas {
        max-width: 100%;
    }

</style>

{% endblock css %}

{% block javascript %}
<script src="{% static 'js/rsvp.js' %}"></script>
<script src="{% static 'js/frame-grab.js' %}"></script>

<script>
    //functions
    function msg( color, msg ) {
        $( "#upload_status" ).attr( 'class', '' );
        $( "#upload_status" ).addClass( 'p-2' );
        $( "#upload_status" ).addClass( color );
        $( "#upload_status" ).text( msg );
    }

    function getExtension( str ) {
        /**
         * checks a given filename for supported file extensions
         * @param (str : string) string containing full filename with extensions
         * @returns found extension or false
         * */

        let lst = [ '.mp4', '.mkv', 'webm' ];
        let substr = str.substring( str.length - 4 );

        for ( let i of lst ) {
            //could also use str.endsWith() method
            if ( substr.toLowerCase().includes( lst[ i ] ) ) {
                return lst[ i ];
            }
        }

        alert( 'file type not supported. Supported file types' +
            ' are: \n -> .mp4 \n -> .mkv \n -> .webm' );
        return false;
    }


    function paintFileDetail( filename, size ) {
        let nm = filename + ` | ${size} Mb`;

        if ( filename.length > 44 ) {
            nm = filename.substring( 0, 30 ) + `... | ${size} Mb`;
        }

        $( "#vid_detail" ).text( nm ).removeClass( 'd-none' );
    }

    function grabFrame( file ) {
        $( "#frameGrabs" ).html( '' );
        $( "#videoContainer" ).html( '' );
        $( "#grab_btn" ).removeClass( "d-none" );

        FrameGrab.blob_to_video( file ).then(
            function videoRendered( videoEl ) {
                var frameGrabInstance = new FrameGrab( {
                    video: videoEl
                } );

                videoEl.setAttribute( "controls", "" );
                document.getElementById( "videoContainer" ).appendChild( videoEl );

                $( "#frame_group" ).removeClass( "d-none" );

                document.getElementById( "grabCurrentFrame" ).onclick = function () {
                    frameGrabInstance.grab_now( "canvas" ).then(
                        function grabbed( itemEntry ) {
                            document.getElementById( "frameGrabs" ).appendChild( itemEntry
                                .container );

                            $( "#grab_btn" ).toggleClass( "d-none" );
                        },


                        function failedToGrab( reason ) {
                            alert( reason );
                        }
                    );

                };
            },

            function videoFailedToRender( reason ) {
                // TODO handle failure to convert the file to a video element
                alert( reason );
            }
        );

    }


    function drawImage() {
        let img = document.getElementById( "thumbnail" );
        let canvas = document.getElementsByTagName( 'canvas' );

        img.setAttribute( "src", canvas.toDataURL( 'image/png' ) );

        // canvas.toBlob( function ( blob ) {
        //     let url = URL.createObjectURL( blob );

        //     img.onload = function () {
        //         // no longer need to read the blob so it's revoked
        //         URL.revokeObjectURL( url );
        //     };

        //     img.src = url;
        // } );
    }

    // replace with grabFrame
    // function generateThumbnail() {
    //     let video = document.getElementById( "video_preview" ),
    //         canvas = document.getElementById( "video_canvas" ),
    //         img = document.getElementById( "video_thumbnail" );
    //     let c_ctx = canvas.getContext( '2d' );

    //     // Video metadata is loaded
    //     video.addEventListener( 'loadedmetadata', function () {
    //         // Set canvas dimensions same as video dimensions
    //         canvas.width = video.videoWidth;
    //         canvas.height = video.videoHeight;

    //         this.currentTime = 17;
    //     } );

    //     img.removeAttribute( "hidden" );
    //     c_ctx.drawImage( video, 0, 0, video.videoWidth, video.videoHeight );
    //     img.setAttribute( "src", canvas.toDataURL() );
    //     $( "#auto_text" ).removeClass( "d-none" );
    // }

    // ajax video upload function
    function uploadVideo() {
        // Make the ajax call
        $.ajax( {
            url: "{% url 'library:upload_video' %}",
            type: 'POST',
            beforeSend: function () {
                msg( "bg-warning", "Please wait. Video uploading..." );
            },
            success: function ( r ) {
                msg( "bg-success", "video upload successful!" );
                $( '#video_form' )[ 0 ].reset();
            },
            data: new FormData( $( '#video_form' )[ 0 ] ),
            cache: false,
            contentType: false,
            processData: false,
        } ).fail( function ( msg ) {
            msg( "bg-danger", 'Error. All fields are required' );
        } );
    }


    // video upload click
    $( "#select_btn" ).click( () => {
        $( "#videofile" ).click();
    } );


    // video upload trigger
    let video = document.getElementById( 'videofile' );
    video.addEventListener( 'change', function () {

        let file = this.files[ 0 ];
        let size = Math.round( file.size / 1000000 );

        if ( size > 302 ) {
            alert( `file size (${ size} MB) is above the maximum allowed (302 MB)` );
            return false;
        }

        // fill in title field with file title if its empty
        if ( !$( "#title" ).val() ) {
            let ext = getExtension( file.name );
            if ( ext ) {
                document.getElementById( "title" ).value = file.name.replace( ext, "" );
            }
        }

        paintFileDetail( file.name, size );
        grabFrame( file );
        drawImage();

    } );


    // video validation
    $( "#vid_submit_btn" ).click( function () {

        if ( $( "#title" ).val() == "" ) {
            msg( "bg-danger", "Video title is required!" );
        } else if ( $( "#desc" ).val() == "" ) {
            msg( "bg-danger", "Video description is required" );
        } else if ( $( "#videofile" ).val() == "" ) {
            msg( "bg-danger", "You must select a video file" );
        } else {
            uploadVideo();
        }

    } );

</script>
{% endblock %}



{% block content %}

<div class="row mt-4 pt-md-4">
    <div class="col-md-2"></div>
    <div class="col-md-8 col-sm-12">
        <div class="bg-white rounded shadow-sm text-center pb-1">
            <h4 class="pt-3">Video upload</h4>

            <div class="row">
                <div class="col-md-7">
                    <form action="" id="video_form" method="POST" enctype="multipart/form-data">
                        {% csrf_token%}

                        <div class="text-left form-group col-12">
                            <small class="form-text text-muted">Title</small>
                            <input name="title" placeholder="enter video title" class="form-control" maxlength="100"
                                required id="title">
                        </div>
                        <div class="text-left form-group col-12">
                            <small class="form-text text-muted">Description</small>
                            <textarea name="description" rows="5" placeholder="description" class="form-control"
                                maxlength="500" id="desc" required></textarea>
                        </div>

                        <!-- hidden essential inputs -->
                        <input type="file" name="video" id="videofile" hidden class=""
                            accept="video/mp4, video/mkv, video/webm">

                        <img src="#" name="thumbnail" id="thumbnail" />

                        <!-- <div class="form-group mb-1">
                            <label for="auto-generate" class="form-label">Auto generate video thumbnail</label>
                            <input type="checkbox" checked name="auto-generate" id="auto-generate">
                        </div> -->

                    </form>

                    <!-- video upload -->
                    <button class="btn waf-btn-prim" id="select_btn">
                        <span class="fas fa-video"></span>
                        Select Video file
                    </button>

                    <p id="vid_detail" class="p-2 mt-2 d-none">
                    </p>

                </div>
                <div class="col-md-5">

                    <section id="frame_group" class="d-none">
                        <div id="videoContainer">
                        </div>
                        <hr>
                        <span id="grab_btn" class="d-none">
                            <p class="small text-primary m-2">play or seek (forward/rewind) to a desireable point in the
                                video n click 'Get Frame' to generate a thumbnail (used as your video img in the
                                library)</p>
                            <button id="grabCurrentFrame" class="mb-1 btn btn-sm btn-outline-secondary">
                                <span class="fas fa-copy"></span> Get frame</button>
                        </span>
                        <div id="frameGrabs"></div>
                    </section>

                    <!-- <canvas id="video_canvas" hidden></canvas>
                    <img src="" alt="auto generated video thumbnail" id="video_thumbnail" style="max-width: 100%;"
                        hidden> -->
                    <!-- <span class="d-block text-success"><em class="d-none" id="auto_text">Auto generated
                            thumbnail</em></span> -->

                    <p class="small text-left p-3">
                        Upload a short lesson or educative video to the library.
                        For maximum impact, you are encouraged to keep video duration down to a max
                        of 4 mins (not a restriction).
                    </p>

                    <div class="mb-2">
                        <a href="{% url 'library:index' %}" class="mr-2 btn btn-outline-secondary">Go
                            back
                            <span class="fas fa-arrow-left">
                            </span>
                        </a>
                        <button class="btn btn-primary" type="submit" id="vid_submit_btn">
                            Upload
                        </button>
                    </div>

                    <div class="my-2 text-white">
                        <p class="" id="upload_status"></p>
                    </div>

                </div>

            </div>
        </div>
        <div class="col-md-2"></div>
    </div>

    {% endblock %}

templates/library/videos.html
{% load static %}

{% block content %}
<!-- Videos Section -->
<div class="col-md-9 col-12">

    <div class="row">

        <div class="col-md-3">
            <a href="{% url 'library:video' 103248 %}">
                <div class="card shadow mb-3" style="width: 13rem; height: 15rem;">
                    <img src="{% static '/img/img2.jpg' %}" class="card-img-top card-img" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Video title</h5>
                        <p class="card-text">sample content</p>
                    </div>
                </div>
            </a>
        </div>

    </div>

</div>

<!-- Recommended section -->
<div class="col-md-3 col-12">

</div>

{% endblock content %}

templates/library/watch.html
{% extends '../_base.html' %}
{% load static %}

{% block title %}
{{vid.title}}
{% endblock %}



{% block javascript %}
<script src="{% static 'js/app/watch.js' %}">
</script>
<script>
    let video = document.getElementById( 'videoplayer' );

    video.addEventListener( 'loadedmetadata', fetchRelatedVideo( this ) );
    video.addEventListener( 'play', countView( video.getAttribute( "data-vidkey" ),
        "{% url 'library:view_count' %}" ) );

</script>
{% endblock %}



{% block fluid %}

<div class="row pt-3 bg-dark text-white-50">
    <div class="container">
        <div class="row">
            <section class="col-md-8 pb-2 px-0">
                <!-- video player -->
                <h3 class="text-white">Load dark navbar</h3>
                {% include 'library/partials/videoplayer.html' %}
            </section>

            <section class="col-md-4">
                <form action="" hidden>
                    {% csrf_token %}
                </form>
                <!-- other videos -->
                <p>Other Videos</p>
                <hr class="bg-secondary">
                {% for i in related %}
                <a href="{% url 'library:watch' i.id %}" class="related_video" title="{{i.title}}">
                    <div class="row no-gutters mb-2" style="max-width: 540px;">
                        <div class="col-4 p-0 m-0">
                            <img src="{% static '/img/img2.jpg' %}" class="card-img" alt="{{i.title}} image">
                        </div>
                        <div class="col-8 pl-1">
                            <div class="py-0">
                                <p class="videotitle mb-0 text-white">{{i.title}}</p>
                                <div class="text-white-50">
                                    <span class="d-block pb-0 mb-0">{{i.user.username}}</span>
                                    <small class="pt-0 mt-0">
                                        {% if i.view_count != 1 %}
                                        {{i.view_count}} views
                                        {% else %}
                                        {{i.view_count}} view
                                        {% endif %}
                                    </small>
                                    <small class="text-muted">{{i.publish_date}}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                </a>

                {% endfor %}
            </section>
        </div>
    </div>
</div>



{% endblock fluid %}

templates/library/watch_broken.html
{% extends '../_base.html' %}

{% load static %}

{% block fluid %}

<div class="row pt-3 bg-dark text-white-50">
    <div class="container">
        <div class="row">
            <section class="col-12 p-5 mb-5">
                <h3 class="text-danger">
                    Watch is broken!
                </h3>
                <a href="{% url 'library:index'%}" class="btn btn-danger">
                    Get me out of here!
                </a>
            </section>
        </div>
    </div>
</div>

{% endblock fluid %}